### ISSUE TITLE
Fails to compile with PSRDADA enabled

### ISSUE THREAD

**Issue by loostrum** [AA-ALERT/RFIm#6]
CMake doesn't add PSRDADA libraries, so compilation fails when PSRDADA is enabled. Can be fixed by adding the following to CMakeLists.txt after the first `set(TARGET_LINK_LIBRARIES)` line (copied from AMBER):
```
if($ENV{PSRDADA})
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_PSRDADA")
  set(TARGET_LINK_LIBRARIES ${TARGET_LINK_LIBRARIES} psrdada cudart)
endif()
```

**Comment by isazi** [comment]
Fixed.
